.PHONY: clean All

All:
	@echo "----------Building project:[ labyWithClassParent - Debug ]----------"
	@cd "labyWithClassParent" && "$(MAKE)" -f  "labyWithClassParent.mk"
clean:
	@echo "----------Cleaning project:[ labyWithClassParent - Debug ]----------"
	@cd "labyWithClassParent" && "$(MAKE)" -f  "labyWithClassParent.mk" clean
