.PHONY: clean All

All:
	@echo "----------Building project:[ astart - Debug ]----------"
	@cd "astart" && "$(MAKE)" -f  "astart.mk"
clean:
	@echo "----------Cleaning project:[ astart - Debug ]----------"
	@cd "astart" && "$(MAKE)" -f  "astart.mk" clean
