.PHONY: clean All

All:
	@echo "----------Building project:[ menuClassSchool - Debug ]----------"
	@cd "menuClassSchool" && "$(MAKE)" -f  "menuClassSchool.mk"
clean:
	@echo "----------Cleaning project:[ menuClassSchool - Debug ]----------"
	@cd "menuClassSchool" && "$(MAKE)" -f  "menuClassSchool.mk" clean
