.PHONY: clean All

All:
	@echo "----------Building project:[ praticeHeterogeneCollection - Debug ]----------"
	@cd "praticeHeterogeneCollection" && "$(MAKE)" -f  "praticeHeterogeneCollection.mk"
clean:
	@echo "----------Cleaning project:[ praticeHeterogeneCollection - Debug ]----------"
	@cd "praticeHeterogeneCollection" && "$(MAKE)" -f  "praticeHeterogeneCollection.mk" clean
