.PHONY: clean All

All:
	@echo "----------Building project:[ mysteriesWords - Debug ]----------"
	@cd "mysteriesWords" && "$(MAKE)" -f  "mysteriesWords.mk"
clean:
	@echo "----------Cleaning project:[ mysteriesWords - Debug ]----------"
	@cd "mysteriesWords" && "$(MAKE)" -f  "mysteriesWords.mk" clean
