.PHONY: clean All

All:
	@echo "----------Building project:[ JSFileGenerator - Debug ]----------"
	@cd "JSFileGenerator" && "$(MAKE)" -f  "JSFileGenerator.mk"
clean:
	@echo "----------Cleaning project:[ JSFileGenerator - Debug ]----------"
	@cd "JSFileGenerator" && "$(MAKE)" -f  "JSFileGenerator.mk" clean
