.PHONY: clean All

All:
	@echo "----------Building project:[ mysterieswords - Debug ]----------"
	@cd "mysterieswords" && "$(MAKE)" -f  "mysterieswords.mk"
clean:
	@echo "----------Cleaning project:[ mysterieswords - Debug ]----------"
	@cd "mysterieswords" && "$(MAKE)" -f  "mysterieswords.mk" clean
