.PHONY: clean All

All:
	@echo "----------Building project:[ alogorithm - Debug ]----------"
	@cd "alogorithm" && "$(MAKE)" -f  "alogorithm.mk"
clean:
	@echo "----------Cleaning project:[ alogorithm - Debug ]----------"
	@cd "alogorithm" && "$(MAKE)" -f  "alogorithm.mk" clean
