.PHONY: clean All

All:
	@echo "----------Building project:[ menuClassEleve - Debug ]----------"
	@cd "menuClassEleve" && "$(MAKE)" -f  "menuClassEleve.mk"
clean:
	@echo "----------Cleaning project:[ menuClassEleve - Debug ]----------"
	@cd "menuClassEleve" && "$(MAKE)" -f  "menuClassEleve.mk" clean
