.PHONY: clean All

All:
	@echo "----------Building project:[ algo-simple - Debug ]----------"
	@cd "algo-simple" && "$(MAKE)" -f  "algo-simple.mk"
clean:
	@echo "----------Cleaning project:[ algo-simple - Debug ]----------"
	@cd "algo-simple" && "$(MAKE)" -f  "algo-simple.mk" clean
